### ISSUE TITLE
.esdoc.json versus esdoc.json

### ISSUE THREAD

**Issue by RichardMarks** [esdoc/esdoc-hosting#10]
I prefer that configuration files all have a dot prefix''and ESDoc hosting is looking for esdoc.json

Could you add an exception for `.esdoc.json` as well? Or better, add a field that lets the user say what their configuration file is called during the hosting generation step?

**Comment by h13i32maru** [comment]
@RichardMarks Sorry for late reply.
ESDoc v0.5 supports `.esdoc.json`. Please check it.
https://esdoc.org/manual/usage/usage.html#configuration
