### ISSUE TITLE
esdoc fails permanent for git url git@github.com:js-joda/js-joda.git

### ISSUE THREAD

**Issue by pithu** [esdoc/esdoc-hosting#11]
Generating the esdoc for the repository  git@github.com:js-joda/js-joda.git fails when its triggered via the online hosting service page -> -> https://doc.esdoc.org/-/generate.html fails always.

In the local working copy the generation of the esdoc works fine.

is that a timeout issue because the documentation is to large ?

**Comment by h13i32maru** [comment]
@pithu Sorry for late reply.
Just now, I success to generate a documentation from your repository.
https://doc.esdoc.org/github.com/js-joda/js-joda/

Please check again. If is problem, I re-open this issue.
