### ISSUE TITLE
Says success but does not update docs

### ISSUE THREAD

**Issue by letmaik** [esdoc/esdoc-hosting#13]
git@github.com:Reading-eScience-Centre/covjson-reader.git

The docs are just not updated even though it said "success!"

**Comment by h13i32maru** [comment]
@letmaik Sorry for late reply.
Just now, I success to generate documentation from your repository.
https://doc.esdoc.org/github.com/Reading-eScience-Centre/covjson-reader/

Please check again. If is problem, I re-open this issue.
