### ISSUE TITLE
ESDoc fails for git@github.com:acbabis/roguelike.git

### ISSUE THREAD

**Issue by aebabis** [esdoc/esdoc-hosting#14]
ESDoc works locally but fails with the public generator

**Comment by aebabis** [comment]
It looks like it uploaded (https://doc.esdoc.org/github.com/acbabis/roguelike/) but the web app for the generator says it failed.

**Comment by aebabis** [comment]
This is still happening. The documentation and badge update, but the generator web app says that it failed.

**Comment by h13i32maru** [comment]
@tomByrer Sorry for late reply.

Now, I generated documentation from your repository.
https://doc.esdoc.org/github.com/acbabis/roguelike/

Please check again. If is problem, I re-open this issue.
