### ISSUE TITLE
Generation doesn't start in Safari 8.0.8 on OS X 10.10.5

### ISSUE THREAD

**Issue by balazsbotond** [esdoc/esdoc-hosting#2]
If I paste the repository URL into the text field on the generation page and click the Generate button, I see no change on the page. If I open Developer Tools, there is a JavaScript error on the console:

```
ReferenceError: Can't find variable: ESDoc - generate.html:81
```

Generation works perfectly in Chrome on the same OS.

**Comment by h13i32maru** [comment]
@balazsbotond Thanks for this issue!
I fixed it.

Thanks :smile:

**Comment by balazsbotond** [comment]
I can confirm that it works now. Thanks for fixing it so quickly! :)
