### ISSUE TITLE
Badges are out of date in GitHub README files

### ISSUE THREAD

**Issue by balazsbotond** [esdoc/esdoc-hosting#3]
After regenerating the documentation, the coverage badge is not updated on GitHub. If I understand correctly, this can be solved by adding a `Cache-Control: no-cache` header to the response according to this issue: https://github.com/github/markup/issues/224

Thanks!

**Comment by h13i32maru** [comment]
@balazsbotond Hi! Thanks for this issue!
I added `no-cache` to badge response :+1:

**Comment by balazsbotond** [comment]
Hi @h13i32maru, thanks for fixing it! I have just checked and it works perfectly.
