### ISSUE TITLE
self-hosting documentation fails

### ISSUE THREAD

**Issue by nickooms** [esdoc/esdoc-hosting#4]
self-hosting documentation fails without a clear error message for my repository :
git@github.com:nickooms/world-builder.git

**Comment by h13i32maru** [comment]
@nickooms Hi! Thanks for this issue!
`esdoc.json` in your repository is invalid. Please fix it and try again.
<img width="456" alt="2015-10-05 0 01 54" src="https://cloud.githubusercontent.com/assets/985170/10268467/552b8cca-6af4-11e5-9fce-f3db01296a20.png">
