### ISSUE TITLE
Automatic builds?

### ISSUE THREAD

**Issue by n1k0** [esdoc/esdoc-hosting#6]
It would be great if docs could be generated and updated automatically each time a repo's master branch is updated, a little like how [readthedocs](http://readthedocs.org/) works.

**Comment by h13i32maru** [comment]
@n1k0 Hi! Thanks for this issue. And sorry late reply.
I do not support to automatically update. Because a repo's master and released package in npm may be different. 

However if I provide update API, is your request solved by it?

**Comment by n1k0** [comment]
> However if I provide update API, is your request solved by it?

Yes, so that would become scriptable, and we could trigger publication from a successful travis master build for instance.

PS: forgot to thank you for this awesome project, love from Mozilla folks sent your way.

**Comment by h13i32maru** [comment]
OK, I will support it in future version.

**Comment by n1k0** [comment]
Awesome!

**Comment by h13i32maru** [comment]
@n1k0 Sorry for late reply. I can not automatic build because I have no time for implementation it.
However the below API may help you. Please check it.

```
curl 'https://doc.esdoc.org/api/create' -X POST --data 'gitUrl=git%40github.com%3Aesdoc%2Fesdoc.git'
```

If is problem, I re-open this issue.

**Comment by h13i32maru** [comment]
> PS: forgot to thank you for this awesome project, love from Mozilla folks sent your way.

Wow! That's great thanks!
