### ISSUE TITLE
free hosting, pricing etc.

### ISSUE THREAD

**Issue by ouhouhsami** [esdoc/esdoc-hosting#8]
Hi there, 

I have a question regarding the hosting of esdoc hosting: have you got a plan to make this project freely available for open source projects after the beta phase? 
I'd like to use the future github hook you seem working on to automate the publishing of esdoc, but I'd like to have better understanding of your goals.

Cheers,

**Comment by h13i32maru** [comment]
@ouhouhsami Hi! Thanks for this question.

> have you got a plan to make this project freely available for open source projects after the beta phase? 

I do not plan to make this hosting pay. So the hosting is free.

> you seem working on to automate the publishing of esdoc

Yes, but I have no time at now... Please wait a moment.

Thanks.

**Comment by h13i32maru** [comment]
> to automate the publishing of esdoc

Sorry, I still have no time for it. Please use generate API.

```
curl 'https://doc.esdoc.org/api/create' -X POST --data 'gitUrl=git%40github.com%3Aesdoc%2Fesdoc.git'
